name: compile tools


on:
  workflow_dispatch:
  schedule:
    - cron: "0 0 1 * *"
  push:
    paths:
      - shared/tools/**

jobs:
    build:
      runs-on: ubuntu-latest
      strategy:
        matrix:
          version: [full, minimal]  # Full vs Minimal
          type: [debug,release]  # Debug vs Release
      name: Build v${{ github.run_number }}-${{ matrix.version }}-${{ matrix.type }} Build
  
      steps:
        - name: Checkout code
          uses: actions/checkout@v2
        - uses: docker/setup-qemu-action@v2
        - uses: docker/setup-buildx-action@v2
          with:
            buildkitd-flags: --debug

        - name: Set environment variables
          run: |
            export RUN_NUMBER=${{ github.run_number }}"
            export MATRIX_VERSION=${{ matrix.version }}"
            export MATRIX_TYPE=${{ matrix.type }}"

        - name: Login to GHCR
          run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin

        - name: Dockerize the Tarball
          working-directory: shared/tools
          run: |
            # Build the Docker image
            docker buildx build --platform linux/amd64,linux/arm64 \
            --build-arg RUN_NUMBER=${{ github.run_number }} \
            --build-arg MATRIX_VERSION=${{ matrix.version }} \
            --build-arg MATRIX_TYPE=${{ matrix.type }} \
            -t ghcr.io/coldhost/tools-cli:v${{ github.run_number }}-${{ matrix.version }}-${{ matrix.type }} .

        - name: Push to GHCR
          run: |
            docker tag ghcr.io/coldhost/tools-cli:v${{ github.run_number }}-${{ matrix.version }}-${{ matrix.type }} ghcr.io/coldhost/tools-cli:latest-${{ matrix.version }}-${{ matrix.type }}
            docker tag ghcr.io/coldhost/tools-cli:v${{ github.run_number }}-${{ matrix.version }}-${{ matrix.type }} ghcr.io/coldhost/tools-cli:v${{ github.run_number }}-${{ matrix.version }}-${{ matrix.type }}
            docker tag ghcr.io/coldhost/tools-cli:v${{ github.run_number }}-${{ matrix.version }}-${{ matrix.type }} ghcr.io/coldhost/tools-cli:${{ github.run_number }}-${{ matrix.version }}-${{ matrix.type }}

            docker push ghcr.io/coldhost/tools-cli:latest-${{ matrix.version }}-${{ matrix.type }}
            docker push ghcr.io/coldhost/tools-cli:v${{ github.run_number }}-${{ matrix.version }}-${{ matrix.type }}
            docker push ghcr.io/coldhost/tools-cli:${{ github.run_number }}-${{ matrix.version }}-${{ matrix.type }}
