name: compile tools


on:
    push:
      branches:
        - main
      paths:
        - shared/tools/
    workflow_dispatch:
  
jobs:
    build:
      runs-on: ubuntu-latest
      strategy:
        matrix:
          version: [full, minimal]  # Full vs Minimal
          debug: [true, false]  # Debug vs Release
      name: Build ${{ matrix.version }} ${{ matrix.debug }} Build
  
      steps:
        - name: Checkout code
          uses: actions/checkout@v2
  
        - name: Generate config.yaml for ${{ matrix.version }} ${{ matrix.debug }}
          run: |
            VERSION=$(date +%Y%m%d%H%M%S)  # Use timestamp for version
            DEBUG=${{ matrix.debug }}  # Set debug flag based on matrix value
            MODULES=$(ls modules/ | grep -v '^\.' | tr '\n' ',' | sed 's/,$//')
  
            echo "version: \"$VERSION\"" > config.yaml
            echo "debug: $DEBUG" >> config.yaml
            echo "modules:" >> config.yaml
  
            if [ -n "$MODULES" ]; then
              IFS=',' read -ra MODULE_LIST <<< "$MODULES"
              for MODULE in "${MODULE_LIST[@]}"; do
                echo "  - $MODULE" >> config.yaml
              done
            else
              echo "  - No modules" >> config.yaml
            fi
  
            cat config.yaml
  
        - name: Install dependencies
          run: |
            sudo apt-get install yq
            pip install -r requirements.txt
  
        - name: Build ${{ matrix.version }} ${{ matrix.debug }}
          run: |
            chmod +x build.sh
            ./build.sh --config config.yaml

        - name: Login to GHCR
          run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin

        - name: Upload Binary to GHCR
          run: |
            echo "Pushing tarball to GHCR..."
            docker build -t ghcr.io/coldhost/tools-binary:latest .
            docker push ghcr.io/coldhost/tools-binary:latest
