name: build java
on:
  workflow_dispatch:
  schedule:
    - cron: "0 0 1 * *"
  push:
    branches:
      - master
    paths:
      - java/**
jobs:
  push:
    name: "yolks:java_${{ matrix.tag }}"
    runs-on: ubuntu-latest
    permissions:
      packages: write
    strategy:
      fail-fast: false
      matrix:
        tag:
          - 8
          - 8j9
          - 11
          - 11j9
          - 16
          - 17
          - 17j9
          - 18
          - 18j9
          - 19
          - 19j9
          - 21
          - 23
    steps:
      - uses: actions/checkout@v3
      - uses: docker/setup-qemu-action@v2
      - uses: docker/setup-buildx-action@v2
        with:
          buildkitd-flags: --debug
      - uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.REGISTRY_TOKEN }}
      - name: Get Commit info
        run: |
          COMMIT_COUNT=${{ github.run_number }} && echo "$COMMIT_COUNT" > java/commit_count.txt
          COMMIT_MESSAGE="${{ github.event.head_commit.message || 'No commit message available' }}" && echo "$COMMIT_MESSAGE" > java/commit_message.txt
      - uses: docker/build-push-action@v4
        with:
          context: ./java
          file: ./java/${{ matrix.tag }}/Dockerfile
          platforms: linux/amd64
          push: true
          tags: |
            ghcr.io/coldhost/yolks:java_${{ matrix.tag }}
          build-args: |
