name: build nodejs
on:
  workflow_dispatch:
  schedule:
    - cron: "0 0 1 * *"
  push:
    branches:
      - master
    paths:
      - nodejs/*
jobs:
  push:
    name: "yolks:nodejs_${{ matrix.tag }}"
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        tag:
          - 12
          - 14
          - 15
          - 16
          - 17
          - 18
          - 20
          - 22
          - 23
          - discord.js-12
          - discord.js-14
          - discord.js-15
          - discord.js-16
          - discord.js-17
          - discord.js-18
          - discord.js-20
          - discord.js-22
          - discord.js-23
    steps:
      - uses: actions/checkout@v3
      # Setup QEMU for ARM64 Build
      - uses: docker/setup-qemu-action@v2
      - uses: docker/setup-buildx-action@v2
        with:
          buildkitd-flags: --debug
      - uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.REGISTRY_TOKEN }}
      - name: Get Commit info
        run: |
          COMMIT_COUNT=${{ github.run_number }} && echo "$COMMIT_COUNT" > nodejs/commit_count.txt
          COMMIT_MESSAGE="${{ github.event.head_commit.message || 'No commit message available' }}" && echo "$COMMIT_MESSAGE" > nodejs/commit_message.txt
      - uses: docker/build-push-action@v4
        with:
          context: ./nodejs
          file: ./nodejs/${{ matrix.tag }}/Dockerfile
          platforms: linux/amd64,linux/arm64
          push: true
          tags: |
            ghcr.io/coldhost/yolks:nodejs_${{ matrix.tag }}