name: build websites
on:
  workflow_dispatch:
  schedule:
    - cron: "0 0 1 * *"
  push:
    branches:
      - master


jobs:
  push:
    name: "yolks:${{ matrix.websites }}"
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        websites:
            - azuriom-php8.4
            - azuriom-php8.3
            - azuriom-php8.2
    steps:
      - uses: actions/checkout@v3
      - uses: docker/setup-qemu-action@v2
      - uses: docker/setup-buildx-action@v2
        with:
          buildkitd-flags: --debug
      - uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.REGISTRY_TOKEN }}
      - uses: docker/build-push-action@v4
        with:
          context: ./oses/${{ matrix.websites }}
          file: ./websites/${{ matrix.websites }}/Dockerfile
          platforms: linux/amd64,linux/arm64
          push: true
          tags: |
            ghcr.io/pterodactyl/yolks:${{ matrix.websites }}
